name: Update Rule and Proxy

on:
  push:
    branches:
      - main  # 根据你的分支名称调整
  workflow_dispatch: # 手动触发

jobs:
  update-rule-and-proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch mydirect.list content
      run: |
        curl -o mydirect.list https://raw.githubusercontent.com/wolfydw/rule/main/mydirect.list

    - name: Fetch myproxy.list content
      run: |
        curl -o myproxy.list https://raw.githubusercontent.com/wolfydw/rule/main/myproxy.list

    - name: Format and update clash mydirect.txt
      run: |
        mkdir -p clash
        echo "payload:" > clash/mydirect.txt
        sed 's/^/  - /' mydirect.list | sed 's/^  - #/#/' >> clash/mydirect.txt
        # 替换作者信息中的 "-" 符号
        sed -i 's/^  - # AUTHOR:/  # AUTHOR:/' clash/mydirect.txt
        sed -i 's/^  - # REPO:/  # REPO:/' clash/mydirect.txt
        sed -i 's/^  - # https/  # https/' clash/mydirect.txt

    - name: Format and update clash myproxy.txt
      run: |
        echo "payload:" > clash/myproxy.txt
        sed 's/^/  - /' myproxy.list | sed 's/^  - #/#/' >> clash/myproxy.txt
        # 替换作者信息中的 "-" 符号
        sed -i 's/^  - # AUTHOR:/  # AUTHOR:/' clash/myproxy.txt
        sed -i 's/^  - # REPO:/  # REPO:/' clash/myproxy.txt
        sed -i 's/^  - # https/  # https/' clash/myproxy.txt

    - name: Commit changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add clash/mydirect.txt clash/myproxy.txt
        git commit -m "Update clash/mydirect.txt and clash/myproxy.txt from source lists with formatting"
        git push
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
